yc_iam_token: "y0_AgAAAAAL47XHAATuwQAAAAEP4ykMAAAq8Zbr4rFAkIfCv_V_DQ1DojehfQ"

vault_datadog_api_key: "22372426d7592233bd9f60375f5bbc60"

vault_db_connection: "pgsql"
vault_db_host: "127.0.0.1"
vault_db_port: "5432"
vault_db_database: "hexlet_777"
vault_db_username: "postgres"
vault_db_password: "RG2023!"


