app_port: "80"
app_tag: "latest"

datadog_api_key: "88d00d4dbd2af4e9f7945f39ed267e06"
datadog_checks:
  http_check:
    instances:
      - name: http_check_{{ inventory_hostname }}
        url: http://localhost:{{ app_port }}
        timeout: 15
        min_collection_interval: 30

~                                                                                                                                                                                  ~                                                                                                                                                                                  ~                                                                                                                                                                                  ~                                                                                                                                                                                  ~                                                                                                                                                                                  ~                                                                                 
