- hosts: all
  become: yes
  tags: deploy

  tasks:
    - name: Debug db_connection variable
      debug:
        var: db_connection
    - name: create env
      ansible.builtin.template:
        src: templates/env.j2
        dest: .env
        mode: "0644"
    - name: Run laravel app on container
      community.docker.docker_container:
        image: ruslan0688/devops-for-programmers-project-77
        platform: linux/amd64
        name: laravel-app
        state: started
        restart_policy: "always"
        restart: true
        ports:
          - "80:3000"
        env_file: .env

- hosts: webservers
  roles:
    - { role: datadog.datadog, become: yes }
  vars:
    datadog_site: "us5.datadoghq.com"
    datadog_api_key: "{{ datadog_api_key }}"

  tags: datadog
